#!/system/bin/sh

#
# deletes ui sounds dir if exists
# works around current audio bug in mr2
#

if [ -d /system/media/audio/ui ]; then
  mount -o remount,rw /system
  rm -rf /system/media/audio/ui
  mount -o remount,ro /system
fi
