#!/system/xbin/bash

export PATH=/system/xbin:/system/bin

busybox mount / -o remount,rw
mkdir /boot
busybox mount /dev/block/mmcblk0p13 /boot

case "$1" in
    recovery)
        CMD="ClockworkMod"
        ;;
    altos)
        CMD="webOS"
        ;;
    *)
        exit 2
esac

# possibly we need to check if the target exists, but
# currently moboot ignores invalid targets so we are good
echo -n $CMD >/boot/moboot.next
busybox umount /boot
sync
