#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEVICE=topaz

mkdir -p ../../../vendor/hp/$DEVICE/proprietary

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/hp/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/hp/__DEVICE__/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \\
    vendor/hp/__DEVICE__/proprietary/libcamera.so:obj/lib/libcamera.so \\
    vendor/hp/__DEVICE__/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so

#    vendor/hp/__DEVICE__/proprietary/libril.so:obj/lib/libril.so

# All the blobs necessary for topaz
PRODUCT_COPY_FILES += \\
        vendor/hp/__DEVICE__/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \\
        vendor/hp/__DEVICE__/proprietary/libcamera.so:/system/lib/libcamera.so

#        vendor/hp/__DEVICE__/proprietary/libril.so:obj/lib/libril.so \\
#	vendor/hp/__DEVICE__/proprietary/rild:/system/bin/rild


#    vendor/hp/__DEVICE__/proprietary/agps_rm:/system/etc/agps_rm \\
#    vendor/hp/__DEVICE__/proprietary/awb_camera:/system/bin/awb_camera \\
#    vendor/hp/__DEVICE__/proprietary/bma150_usr:/system/bin/bma150_usr \\
#    vendor/hp/__DEVICE__/proprietary/btld:/system/bin/btld \\
#    vendor/hp/__DEVICE__/proprietary/charging:/system/bin/charging \\
#    vendor/hp/__DEVICE__/proprietary/dcvs:/system/bin/dcvs \\
#    vendor/hp/__DEVICE__/proprietary/dcvsd:/system/bin/dcvsd \\
#    vendor/hp/__DEVICE__/proprietary/hp_ebdlogd:/system/bin/hp_ebdlogd \\
#    vendor/hp/__DEVICE__/proprietary/hpbatt:/system/bin/hpbatt \\
#    vendor/hp/__DEVICE__/proprietary/hdmid:/system/bin/hdmid \\
#    vendor/hp/__DEVICE__/proprietary/ipd:/system/bin/ipd \\
#    vendor/hp/__DEVICE__/proprietary/ip:/system/bin/ip \\
#    vendor/hp/__DEVICE__/proprietary/logcat2:/system/bin/logcat2 \\
#    vendor/hp/__DEVICE__/proprietary/lsc_camera:/system/bin/lsc_camera \\
#    vendor/hp/__DEVICE__/proprietary/netmgrd:/system/bin/netmgrd \\
#    vendor/hp/__DEVICE__/proprietary/netsharing:/system/bin/netsharing \\
#    vendor/hp/__DEVICE__/proprietary/rmt_storage:/system/bin/rmt_storage \\
#    vendor/hp/__DEVICE__/proprietary/ser2net:/system/bin/ser2net \\
#    vendor/hp/__DEVICE__/proprietary/sound8x60:/system/bin/sound8x60 \\
#    vendor/hp/__DEVICE__/proprietary/load-modem.sh:/system/bin/load-modem.sh \\
#    vendor/hp/__DEVICE__/proprietary/mpdecision:/system/bin/mpdecision \\
#    vendor/hp/__DEVICE__/proprietary/thermald:/system/bin/thermald \\
#    vendor/hp/__DEVICE__/proprietary/qmuxd:/system/bin/qmuxd \\
#    vendor/hp/__DEVICE__/proprietary/usbnet:/system/bin/usbnet \\
#    vendor/hp/__DEVICE__/proprietary/wireless_modem:/system/xbin/wireless_modem \\
#    vendor/hp/__DEVICE__/proprietary/agps_rm:/system/etc/agps_rm \\
#    vendor/hp/__DEVICE__/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \\
#    vendor/hp/__DEVICE__/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \\
#    vendor/hp/__DEVICE__/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \\
#    vendor/hp/__DEVICE__/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \\
#    vendor/hp/__DEVICE__/proprietary/libOmxVdec.so:/system/lib/libOmxVdec.so \\
#    vendor/hp/__DEVICE__/proprietary/libOmxCore.so:/system/lib/libOmxCore.so \\
#    vendor/hp/__DEVICE__/proprietary/libOmxVenc.so:/system/lib/libOmxVenc.so \\
#    vendor/hp/__DEVICE__/proprietary/libC2D2.so:/system/lib/libC2D2.so \\
#    vendor/hp/__DEVICE__/proprietary/libcamera_client.so:/system/lib/libcamera_client.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_imx074_default_video.so:/system/lib/libchromatix_imx074_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_imx074_preview.so:/system/lib/libchromatix_imx074_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_imx105_default_video.so:/system/lib/libchromatix_imx105_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_imx105_preview.so:/system/lib/libchromatix_imx105_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_mt9p012_ar.so:/system/lib/libchromatix_mt9p012_ar.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_mt9p012_default_video.so:/system/lib/libchromatix_mt9p012_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_mt9p012_km_default_video.so:/system/lib/libchromatix_mt9p012_km_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_mt9p012_km_preview.so:/system/lib/libchromatix_mt9p012_km_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_mt9p012_preview.so:/system/lib/libchromatix_mt9p012_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_mt9e013_ar.so:/system/lib/libchromatix_mt9e013_ar.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_mt9e013_default_video.so:/system/lib/libchromatix_mt9e013_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_mt9e013_preview.so:/system/lib/libchromatix_mt9e013_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_mt9t013_default_video.so:/system/lib/libchromatix_mt9t013_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_mt9t013_preview.so:/system/lib/libchromatix_mt9t013_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_ov8810_default_video.so:/system/lib/libchromatix_ov8810_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_ov8810_preview.so:/system/lib/libchromatix_ov8810_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_ov9726_preview.so:/system/lib/libchromatix_ov9726_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_ov9726_video.so:/system/lib/libchromatix_ov9726_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_s5k3e2fx_default_video.so:/system/lib/libchromatix_s5k3e2fx_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_s5k3e2fx_preview.so:/system/lib/libchromatix_s5k3e2fx_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_s5k3h1gx_default_video.so:/system/lib/libchromatix_s5k3h1gx_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_s5k3h1gx_preview.so:/system/lib/libchromatix_s5k3h1gx_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_s5k3h2yx_default_video.so:/system/lib/libchromatix_s5k3h2yx_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_s5k3h2yx_preview.so:/system/lib/libchromatix_s5k3h2yx_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_s5k4e1gx_default_video.so:/system/lib/libchromatix_s5k4e1gx_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_s5k4e1gx_preview.so:/system/lib/libchromatix_s5k4e1gx_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_sn12m0pz_default_video.so:/system/lib/libchromatix_sn12m0pz_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_sn12m0pz_preview.so:/system/lib/libchromatix_sn12m0pz_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_vb6801_default_video.so:/system/lib/libchromatix_vb6801_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_vb6801_preview.so:/system/lib/libchromatix_vb6801_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_vx6953_default_video.so:/system/lib/libchromatix_vx6953_default_video.so \\
#    vendor/hp/__DEVICE__/proprietary/libchromatix_vx6953_preview.so:/system/lib/libchromatix_vx6953_preview.so \\
#    vendor/hp/__DEVICE__/proprietary/libdiag.so:/system/lib/libdiag.so \\
#    vendor/hp/__DEVICE__/proprietary/libdll.so:/system/lib/libdll.so \\
#    vendor/hp/__DEVICE__/proprietary/libdsutils.so:/system/lib/libdsutils.so \\
#    vendor/hp/__DEVICE__/proprietary/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \\
#    vendor/hp/__DEVICE__/proprietary/libgemini.so:/system/lib/libgemini.so \\
#    vendor/hp/__DEVICE__/proprietary/libgsl.so:/system/lib/libgsl.so \\
#    vendor/hp/__DEVICE__/proprietary/libhp_acoustic.so:/system/lib/libhp_acoustic.so \\
#    vendor/hp/__DEVICE__/proprietary/libhp_ril.so:/system/lib/libhp_ril.so \\
#    vendor/hp/__DEVICE__/proprietary/libidl.so:/system/lib/libidl.so \\
#    vendor/hp/__DEVICE__/proprietary/librilswitch.so:/system/lib/librilswitch.so \\
#    vendor/hp/__DEVICE__/proprietary/libganril.so:/system/lib/libganril.so \\
#    vendor/hp/__DEVICE__/proprietary/libkineto.so:/system/lib/libkineto.so \\
#    vendor/hp/__DEVICE__/proprietary/libmmipl.so:/system/lib/libmmipl.so \\
#    vendor/hp/__DEVICE__/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \\
#    vendor/hp/__DEVICE__/proprietary/libmpl.so:/system/lib/libmpl.so \\
#    vendor/hp/__DEVICE__/proprietary/libmpl_jni.so:/system/lib/libmpl_jni.so \\
#    vendor/hp/__DEVICE__/proprietary/libmllite.so:/system/lib/libmllite.so \\
#    vendor/hp/__DEVICE__/proprietary/libmlplatform.so:/system/lib/libmlplatform.so \\
#    vendor/hp/__DEVICE__/proprietary/libnetmgr.so:/system/lib/libnetmgr.so \\
#    vendor/hp/__DEVICE__/proprietary/libposteffect.so:/system/lib/libposteffect.so \\
#    vendor/hp/__DEVICE__/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \\
#    vendor/hp/__DEVICE__/proprietary/libOpenVG.so:/system/lib/libOpenVG.so \\
#    vendor/hp/__DEVICE__/proprietary/libqdp.so:/system/lib/libqdp.so \\
#    vendor/hp/__DEVICE__/proprietary/libqmi.so:/system/lib/libqmi.so \\
#    vendor/hp/__DEVICE__/proprietary/libqmiservices.so:/system/lib/libqmiservices.so \\
#    vendor/hp/__DEVICE__/proprietary/vpimg:/system/etc/vpimg \\
#    vendor/hp/__DEVICE__/proprietary/gps.topaz.so:/system/lib/hw/gps.topaz.so \\
#    vendor/hp/__DEVICE__/proprietary/lights.msm8660.so:/system/lib/hw/lights.msm8660.so \\
#    vendor/hp/__DEVICE__/proprietary/sensors.topaz.so:/system/lib/hw/sensors.topaz.so
EOF

./setup-makefiles.sh
